<!--
/**
 * Copyright ©   All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<?php $isActive = $block->getCmsPageModalIsActive(); ?>
<?php if ($isActive): ?>
    <?php $content = $block->getCmsPageModalContent(); ?>
        <div data-mage-init='{"modals": {}}'></div>
        <div id="popup-modal" style="display: none;">
            <?php echo $content ?>
        </div>
<?php endif; ?>
